### ISSUE TITLE
Add vcloud Example

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-examples/clearwater-nfv-blueprint#24]
Create a new vcloud blueprint:

- [ ] call it `vcloud-clearwater-blueprint.yaml`
- [ ] For the clearwater application, import ```application-blueprint.yaml``` instead of including it in the blueprint. (See [this](https://github.com/cloudify-examples/clearwater-nfv-blueprint/blob/master/azure-blueprints.yaml#L7) example.)
- [ ] Update to use Cloudify 4.0.
- [ ] Create a DSL definitions instead of using a provider context and use get_secret, example:
```yaml
dsl_definitions:
  vcloud_config:
    properties: &vcloud_config
      vcloud_username: { get_secret: vcloud_username }
      vcloud_password: { get_secret: vcloud_password }
      vcloud_url: { get_secret: vcloud_url }
     ...etc...

node_templates:
    common_network:
        type: cloudify.vcloud.nodes.Network
        properties:
            ...etc....
            vcloud_config: *vcloud_config
```
- [ ] Delete the [old](https://github.com/cloudify-examples/clearwater-nfv-blueprint/blob/master/inputs/clearwater51-vcloud-inputs.yaml) vcloud inputs.
- [ ] Create new inputs file. Call the file `vcloud.yaml.example`.
