### ISSUE TITLE
Update Vsphere Example

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-examples/clearwater-nfv-blueprint#25]
Create a new vsphere blueprint:

- [ ] call it `vsphere-clearwater-blueprint.yaml`
- [ ] For the clearwater application, import ```application-blueprint.yaml``` instead of including it in the blueprint. (See [this](https://github.com/cloudify-examples/clearwater-nfv-blueprint/blob/master/azure-blueprints.yaml#L7) example.)
- [ ] Update to use Cloudify 4.0.
- [ ] Create a DSL definitions instead of using a provider context and use get_secret, example:
```yaml
dsl_definitions:
  vsphere_config:
    properties: &vsphere_config
      vsphere_username: { get_secret: vsphere_username }
     ...etc...

node_templates:
    network:
        type: cloudify.vsphere.nodes.Network
        properties:
            ...etc....
            vsphere_config: *vcloud_config
```
- [ ] Create new inputs file. Call the file `vcloud.yaml.example`. Provide comments on how to use it.
